export { Contacto } from './contacto/Contacto';
export { FooterType2 } from './footer/FooterType2';
export { FooterType1 } from './footer/FooterType1';
export { Contacto as ContactoCard } from './inicio/Contacto';
// export { Inicio } from './inicio/Inicio';
export { Proyectos } from './proyectos/Proyectos';
export { Servicio } from './servicios/Servicio';
export { Sidebar } from './sidebar/Sidebar';
export { Experiencia } from './sobremi/Experiencia';
// export { ConoceServicios } from './sobremi/ConoceServicios';
export { Resumen } from './sobremi/Resumen';
export { Aditional } from './sobremi/Aditional';